flasklogin-tutorial/login_tutorial/models.py
from . import db
import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin, db.Model):
  __tablename__ = 'flask_db'

  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(50), nullable=False, unique=False)
  email = db.Column(db.String(40), nullable=False, unique=False)
  password = db.Column(db.String(200), primary_key=False, nullable=False, unique=False)
  website = db.Column(db.String(60), index=False, nullable=True, unique=False)
  createdAt = db.Column(db.DateTime, default=datetime.datetime.now())
  updatedAt = db.Column(
      db.DateTime, default=datetime.datetime.now(), onupdate=datetime.datetime.now)

  def set_password(self, password):
    self.password = generate_password_hash(password, method="sha256")

  def check_password(self, password):
    return check_password_hash(self.password, password)

  def __repr__(self):
    return '<User {}>'.format(self.username)
    

flasklogin-tutorial/login_tutorial/forms.py
from wtforms import Form, StringField, PasswordField, validators,DateField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length, Optional, Required
import datetime

class SignupForm(Form):
  name = StringField('Name', validators=[DataRequired(message=('Enter a fake name or something!'))])
  email = StringField('Email', validators=[Length(min=6, message=('Please enter a valed email address.')),
                                           Email(message='Please enter a valed email address.'),
                                           DataRequired(message=('Please enter a valed email address.'))])
  password = PasswordField('Password', validators=[DataRequired(message='Please enter password'),
                                       Length(min=6, message=('Please select a stronger password')),
                                       EqualTo('confirm', message=('Passwords must match'))])
  confirm = PasswordField('Confirm Your Password',)
  website = StringField('Website', validators=[Optional()])
  submit = SubmitField('Register')

class LoginForm(Form):
  email = StringField('Email', validators=[DataRequired('Please enter a valid email address.'),
                                Email('Please enter a valid email address.')])
  password = PasswordField('Password', validators=[DataRequired('Uhh, your password tho?')])
  submit = SubmitField('Log In')

flasklogin-tutorial/login_tutorial/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap

db = SQLAlchemy()
login_manager = LoginManager()

def create_app():
  app = Flask(__name__, instance_relative_config=False)
  bootstrap = Bootstrap(app)
  app.config.from_object('config.Config')
  db.init_app(app)
  login_manager.init_app(app)


  with app.app_context():

    from . import routes
    from . import auth

    app.register_blueprint(routes.main_bp)
    app.register_blueprint(auth.auth_bp)

    db.create_all()
    return app
    

flasklogin-tutorial/login_tutorial/auth.py
import os
import datetime
from flask import redirect, render_template, flash, Blueprint, request, session, url_for
from flask_login import login_required, logout_user, current_user, login_user
from flask import current_app as app
from werkzeug.security import generate_password_hash, check_password_hash
from flask_assets import Environment, Bundle
from .forms import LoginForm, SignupForm
from .models import db, User
from . import login_manager

auth_bp = Blueprint('auth_bp', __name__, template_folder='templates', static_folder='static')
assets = Environment(app)

@auth_bp.route('/login', methods=['GET', 'POST'])
def login_page():
  if current_user.is_authenticated:
    return redirect(url_for('main_bp.dashboard'))
  login_from = LoginForm(request.form)

  if request.method == 'POST':
    if login_from.validate():
      email = request.form.get('email')
      password = request.form.get('password')
      user = User.query.filter_by(email=email).first()
      if user:
        if user.check_password(password=password):
          login_user(user)
          next = request.args.get('next')
          return redirect(next or url_for('main_bp.dashboard'))
    flash('Invalid user/password combination')
  return render_template('login.html', 
                          form=LoginForm(), 
                          title='Log in | Flask-login Tutorial.', 
                          template='login-page',
                          body="Log in with your User account."
                          )

@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup_page():
  signup_form = SignupForm(request.form)
  if request.method == 'POST':
    if signup_form.validate():
      name = request.form.get('name')
      email = request.form.get('email')
      password = request.form.get('password')
      website = request.form.get('website')
      existing_user = User.query.filter_by(email=email).first()
      if existing_user is None:
        user = User(name = name,
                    email = email,
                    password = generate_password_hash(password, method="sha256"),
                    website = website,
                    
                    )
        db.session.add(user)
        db.session.commit()
        login_user(user)
        return redirect(url_for('main_bp.dashboard'))
      flash('A user already exists with that email address.')
      return redirect(url_for('auth_bp.signup_page'))

  return render_template('/signup.html',
                          title='Create an Account | Flask-Login Tutorial.',
                          form=SignupForm(),
                          templates='signup-page',
                          body="Sign up for a user account.")

@auth_bp.route('/logout')
@login_required
def logout_page():
  logout_user()
  return redirect(url_for('auth_bp.login_page'))

@login_manager.user_loader
def load_user(user_id):
  if user_id is not None:
    return User.query.get(user_id)
  return None

@login_manager.unauthorized_handler
def unauthorized():
  flash('You must be logged in to view that page.')
  return redirect(url_for('auth_bp.login_page'))

flasklogin-tutorial/login_tutorial/routes.py
import os
from flask import Blueprint, render_template
from flask_assets import Environment, Bundle
from flask_login import current_user
from flask import current_app as app
from .models import User
from flask_login import login_required

main_bp = Blueprint('main_bp', __name__,
                    template_folder='templates',
                    static_folder='static')
assets = Environment(app)

@main_bp.route('/', methods=['GET'])
@login_required
def dashboard():
  return render_template('dashboard.html',
                          title='Flask-login Tutorial.',
                          template='dashboard-template',
                          current_user=current_user,
                          body="You are now logged in~")

flasklogin-tutorial/login_tutorial/templates/_formhelpers.html
<!DOCTYPE html>

{% macro render_field(field) %}
<dt>{{ field.label }}
<dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
  <ul class="errors">
    {% for error in field.errors %}
    <li>{{ error }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</dd>
{% endmacro %}

flasklogin-tutorial/login_tutorial/templates/dashboard.html
<!DOCTYPE html>
{% extends "layout.html" %}
{% block pagestyles %}
<!-- <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css"> -->
<link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
<h1>{{body}}</h1>

{% if current_user.is_authenticated %}
<p>Hi {{ current_user.name }}!</p>
<a href="{{ url_for('auth_bp.logout_page') }}">Log out</a>
{% endif %}
{% endblock %}

flasklogin-tutorial/login_tutorial/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block meta %}
  <meta charset="utf-8" />
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge" /> -->
  <title>{{title}}</title>
  <meta name="HandheldFriendly" content="True" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
  <meta name="theme-color" content="#5eb9d7" />
  <link rel="shortcut icon" href="{{ url_for('static', filename='dist/img/favicon.png') }}" type="image/x-icon" />
  {% endblock %}

  {% block pagestyles %}{% endblock %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,500" rel="stylesheet">
</head>

<body class="{{template}}">
  <div class="container">
    {% block content %}{% endblock %}

  </div>
  <!-- Scripts -->
  <script src="{{ url_for('static', filename='dist/js/main.min.js') }}"></script>
  
  {% block additionalscripts %}{% endblock %}
</body>

</html>

flasklogin-tutorial/login_tutorial/templates/login.html
<!DOCTYPE html>
{% extends 'layout.html' %}
{% import "bootstrap/base.html" as wtf %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}

{% block pagestyles %}
{% endblock  %}

{% block content %}
  <div class="formwrapper">
    <form method="post">
      <div class="message">
        {% for message in get_flashed_messages() %}
      </div>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          {{ message }}
        </div>
      {% endfor %}
      <h1>Log in</h1>
      <div class="email">
        <!-- {{ form.email.lebal }}
        {{ form.email(placeholder='youremail@example.com') }} -->
        {{ render_field(form.email, class='form-control',placeholder='youremail@example.com' ) }}

        {% if form.email.errors %}
        <ul class="errors">
          {% for error in form.email.errors  %}<li> {{error}} </li>{% endfor %}
        </ul>
        {% endif %}
      </div>

      <div class="passord">
        <!-- {{ form.password.label }}
        {{ form.password }} -->
        {{ render_field(form.password, class='form-control' ) }}
        {% if form.password.errors %}
        <ul class="errors">
          {% for error in form.password.errors %} <li> {{error}} </li>{% endfor %}
        </ul>
        {% endif %}
      </div>

      <div class="submitbutton">
        <input id="submit" type="submit" value="submit" class="btn btn-info">
      </div>
      </form>
      <div class="loginsigup">
        <span>Don't have an account? <a href="{{url_for('auth_bp.signup_page')}} ">Sign in.</a></span>
      </div>
  </div>
{% endblock  %}

flasklogin-tutorial/login_tutorial/templates/signup.html
<!DOCTYPE html>
{% extends 'layout.html' %}
{% import "bootstrap/base.html" as wtf %}
{% import "bootstrap/wtf.html" as wtf %}
{% from "_formhelpers.html" import render_field %}

{% block pagestyles %}
{% endblock  %}

{% block content %}
  <div class="container">
    <form class="form form-horizontal" method="post">
      <div class="message">
        {% for message in get_flashed_messages() %}
      </div>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          {{ message }}
        </div>
      {% endfor %}
      <h1>Sign Up</h1>

      <div class="name">
        {{ render_field(form.name, class='form-control',placeholder='John Watson' ) }}
        <!-- {{ form.name.label }} -->
        <!-- {{ form.name(placeholder='John Watson') }} -->
        {% if form.name.errors  %}
          <ul class="errors">
            {% for error in form.email.errors %} <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="email">
        
        <!-- {{ form.email.label }}
          {{ form.email(placeholder='youremail@example.com') }} -->
        {{ render_field(form.email, class='form-control',placeholder='youremail@example.com' ) }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.email.errors  %}<li> {{error}} </li>{% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="password">
        <!-- {{ form.password.label }} 
        {{ form.password }} -->
        {{ render_field(form.password, class='form-control' ) }}

        {% if form.password.errors %}
        <ul class="errors">
          {% for error in form.password.errors %} <li> {{error}} </li>{% endfor %}
        </ul>
        {% endif %}
      </div>

      <div class="confirm">
        <!-- {{ form.confirm.label }}
        {{ form.confirm }} -->
        {{ render_field(form.confirm, class='form-control' ) }}
        {% if form.confirm.errors %}
          <ul class="errors">
            {% for error in form.confirm.errors %} <li> {{error}} </li>{% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="website">
        <!-- {{ form.website.label }}
        {{ form.website(placeholder='http://example.com') }} -->
        {{ render_field(form.website, class='form-control',placeholder='http://example.com' ) }}
      </div>

      <div class="submitbutton">
        <input id="submit" type="submit" value="submit" class="btn btn-info">
      </div>
    </form>
    <div class="loginsignup">
      <span>Already have an account? <a href="{{url_for('auth_bp.login_page')}} ">log in.</a></span>
    </div>
  </div>
{% endblock %}